[package]
name = "advent_of_code"
version = "2019.0.0"
authors = ["Charles Pigott <charlespigott@googlemail.com>"]
edition = "2018"

[dependencies]
rayon = "^1.8"
itertools = "^0.12"
permutohedron = "^0.2"
regex = "^1.10"
