[package]
name = "advent_of_code"
version = "2019.0.0"
authors = ["Charles Pigott <charlespigott@googlemail.com>"]

[dependencies]
itertools = "^0.7"
regex = "^0.2"
time = "^0.1"
permutohedron = "^0.2"
