[package]
name = "AdventofCode"
version = "2016.14.0"
authors = ["Charles Pigott <charlespigott@googlemail.com>"]
edition = "2015"

[dependencies]
itertools = "^0.12"
regex = "^1.10"
rust-crypto = "^0.2"
